baseurl = "//puyixiaowo.win/"
languageCode = "en"
title = "飞鸿"
theme = "cleverlee"
paginate = "6" # Number of posts per page
copyright = "&copy; <a href=\"//github.com/ysdxz207\" target=\"_blank\">ysdxz207</a> 2017"
disqusShortname = "shortname"
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
description = "飞鸿的个人主页"


[taxonomies]
    tag = "tags"
    category = "categories"

[Params]



[Params.highlight]
    style = "github"
    languages = ["go", "java", "xml"]


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
	
	recent_articles_size = 10 #最新文章条数
	
	
[[Params.social]]
    url = "/resume/my-resume/"
    fa_icon = "fa-handshake-o"
    title = "我的简历"

[[Params.social]]
    url = "//github.com/ysdxz207?tab=repositories"
    fa_icon = "fa-github"
    title = "我的github主页"

[Params.meta]
    keywords = ["飞鸿", "cleverlee"]

[Params.resources]
    cdn = "//cdn.bootcss.com"